task:
  name: StarX_Auto_Build_Stable_GLB
  # Only manual trigger with input URL
  trigger_type: manual
  environment:
    # Define environment variables
    INPUT_URL: ${INPUT_URL}
  container:
    image: ubuntu:latest
    # Configure additional CPU and memory resources
    cpu: 8
    memory: 16G
  
  # Maximize build space
  maximize_build_space_script:
    - |
      docker rmi `docker images -q` || true
      rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d || true
      apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell mysql* php* || true
      apt -y autoremove --purge || true
      apt -y autoclean || true
      apt clean || true
      # Create swap file for more memory
      dd if=/dev/zero of=/swapfile bs=1M count=1024
      chmod 600 /swapfile
      mkswap /swapfile
      swapon /swapfile

  # Install dependencies
  setup_dependencies_script:
    - apt-get update
    - apt-get install -y software-properties-common git sudo
    - add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - apt-get update
    - apt-get install -y aria2 rclone sshpass wget python3 libc6 libstdc++6 python3-pip dialog libgtk-3-dev aapt busybox brotli zip unzip p7zip-full zipalign zstd bc android-sdk-libsparse-utils xmlstarlet
    - pip3 install ConfigObj telebot

  # Install OpenJDK
  setup_java_script:
    - apt-get install -y openjdk-17-jdk

  # Set timezone
  set_timezone_script:
    - apt-get install -y tzdata
    - ln -fs /usr/share/zoneinfo/Asia/Ho_Chi_Minh /etc/localtime
    - dpkg-reconfigure -f noninteractive tzdata

  # Checkout code and workspace
  checkout_script:
    - git clone https://github.com/${CIRRUS_REPO_FULL_NAME}.git
    # You'll need to set up a Cirrus CI encrypted variable for PRIVATEHMA_TOKEN
    - git clone https://${PRIVATEHMA_TOKEN}@github.com/ndtai1527/xiaomi_starx_hybrid.git

  # Ensure correct permissions
  permissions_script:
    - cd xiaomi_starx_hybrid
    - chmod 777 -R *

  # Run the build process
  build_script:
    - cd xiaomi_starx_hybrid
    - bash caramelGB.sh "$INPUT_URL"

  # Optional: Add artifact upload if needed
  # artifacts:
  #   name: build-outputs
  #   path: xiaomi_starx_hybrid/output/**